version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  consul:
    image: "consul:1.15.4"
    ports:
      - "8500:8500"