version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  consul:
    image: "consul:1.15.4"
    ports:
      - "8500:8500"
  nats:
    image: "nats:latest"
    ports:
      - "4222:4222"
      - "8222:8222"